org: phaselabs
app: classify-serverless
service: classify-serverless

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/classifications"
        - Effect: Allow
          Action:
            - textract:AnalyzeDocument
          Resource: "*"
build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

plugins:
  - serverless-certificate-creator
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline
custom:
  customDomain:
    domainName: ${self:custom.vars.domainName}
    certificateName: ${self:custom.vars.domainName}
    basePath: ''
    createRoute53Record: true
    apiType: http
    endpointType: regional
    stage: prod

  customCertificate:
    certificateName: ${self:custom.vars.domainName}
    hostedZoneIds: ${self:custom.vars.hostedZoneId}
    region: ${aws:region}
    stage: prod
    rewriteRecords: false
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
  vars:
    domainName: filtoor.align.nexus
    hostedZoneId: Z0243682Q9S0F7VQNK6J

functions:
  classify:
    handler: classify.handler
    timeout: 30
    events:
      - httpApi:
          path: /classify
          method: post
  classifications:
    handler: classifications.handler
    timeout: 30
    events:
      - httpApi:
          path: /classifications
          method: post

resources:
  Resources:
    classifications:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: classifications
        AttributeDefinitions:
          - AttributeName: address
            AttributeType: S
        KeySchema:
          - AttributeName: address
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
